name: Ostrov
version: '3.4'
description: Main Ostrov plugin
api-version: '1.21.7'
main: ru.komiss77.Ostrov
bootstrapper: ru.komiss77.boot.OStrap
loader: ru.komiss77.boot.OLoader

dependencies:
  #bootstrap:
  # Let's say that RegistryPlugin registers some data that your plugin needs to use
  # We don't need this during runtime, so it's not required in the server section.
  # However, can be added to both if needed

  # load (BEFORE|AFTER|OMIT): Whether the plugin should load before or after your plugin.
  # required: Whether this plugin is required for your plugin to load.
  # join-classpath: Whether your plugin should have access to their classpath.
  # This is used for plugins that need to access other plugins internals directly.

  server:
    EasyPayments: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
    CrazyAdvancementsAPI: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
    ProCosmetics: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
    dynmap: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
    FastAsyncWorldEdit: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
    WorldGuard: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
    Skills: # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
      load: AFTER
      required: false
      join-classpath: true
